# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160819_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Message'),
        ),
    ]
