# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('goes_id', models.CharField(max_length=8)),
                ('goes_channel', models.PositiveSmallIntegerField()),
                ('goes_spacecraft', models.CharField(choices=[('E', 'East'), ('W', 'West')], default='E', max_length=1)),
                ('arrival_time', models.DateTimeField()),
                ('failure_code', models.CharField(max_length=1)),
                ('signal_strength', models.PositiveSmallIntegerField()),
                ('frequency_offset', models.CharField(max_length=2)),
                ('modulation_index', models.CharField(choices=[('N', 'Normal (60 degrees +/- 5)'), ('L', 'Low (50 degrees)'), ('H', 'High (70 degrees)')], default='N', max_length=1)),
                ('data_quality', models.CharField(choices=[('N', 'Normal (error rate < 10^-6)'), ('F', 'Fair (10^-6 < error rate < 10^-4)'), ('P', 'Poor (error rate > 10^-4)')], default='N', max_length=1)),
                ('data_source', models.CharField(choices=[('LE', 'Cincinnati East; USACE LRD Cincinnati'), ('d1', 'NIFC West Boise ID - Unit 1; NIFC Boise'), ('d2', 'NIFC West Boise ID - Unit 2; NIFC Boise'), ('OW', 'Omaha West; USACE NWO'), ('RE', 'Rock Island East; USACE MVR'), ('RW', 'Rock Island West; USACE MVR'), ('SF', 'West Palm Beach East; SFWMD'), ('UB', 'Ucom Backup @ WCDA; NOAA Wallops CDA'), ('UP', 'Ucom Primary @ WCDA; NOAA Wallops CDA'), ('XE', 'Sioux Falls, East; USGS EROS'), ('XW', 'Sioux Falls, West; USGS EROS'), ('XL', 'Sioux Falls, LRIT; USGS EROS'), ('RL', 'Reston, LRIT; Reston, Virginia')], max_length=2)),
                ('recorded_message_length', models.PositiveSmallIntegerField()),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('message_text', models.TextField()),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate_data.Station')),
            ],
        ),
    ]
