# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0016_auto_20170406_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='short_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
