# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0018_auto_20170610_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='data_source',
            field=models.CharField(choices=[('G', 'GOES satellite message'), ('L', 'Station data log')], default='G', max_length=1),
        ),
    ]
