# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0020_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='data_type',
        ),
        migrations.AddField(
            model_name='stationsensorlink',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='climate_data.DataType'),
        ),
    ]
