# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0022_auto_20170623_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='station_sensor_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='climate_data.StationSensorLink'),
        ),
    ]
