# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0024_auto_20170623_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='bounds',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default='[-2147483647,2147483646]'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='unit',
            field=models.CharField(choices=[('°C', 'degrees Celcius'), ('°F', 'degrees Fahrenheit'), ('K', 'kelvin'), ('km', 'kilometres'), ('m', 'metres'), ('cm', 'centimetres'), ('mm', 'millimetres'), ('°', 'degrees'), ('rad', 'radians'), ('m/s', 'metres per second'), ('km/h', 'kilometres per hour'), ('kPa', 'kilopascals'), ('hPa', 'hectopascals'), ('Pa', 'pascals'), ('bar', 'bar'), ('mbar', 'millibar'), ('W/m^2', 'Watts per square metre'), ('V', 'volts'), ('A', 'amperes'), ('Ω', 'ohms'), ('J', 'joules'), ('W', 'watts'), ('%', 'percent'), (None, 'none')], max_length=40, null=True),
        ),
    ]
