# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0029_auto_20170628_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='short_name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
