# Generated by Django 2.0.1 on 2018-01-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0031_auto_20170727_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='data_source',
            field=models.CharField(choices=[('G', 'GOES satellite message'), ('L', 'Station data log'), ('B', 'Both satellite message and log')], default='G', max_length=1),
        ),
    ]
