# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(max_length=50)),
                ('genus', models.CharField(db_index=True, max_length=50)),
                ('species', models.CharField(db_index=True, max_length=50)),
                ('common_name', models.CharField(max_length=255)),
                ('dth', models.CharField(max_length=10)),
                ('accession', models.PositiveIntegerField(null=True)),
                ('date_collected', models.DateField(null=True)),
                ('collectors', models.TextField()),
                ('map_included', models.NullBooleanField()),
                ('map_reference', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=127)),
                ('township', models.CharField(max_length=127)),
                ('location', models.CharField(max_length=127)),
                ('habitat', models.CharField(max_length=127)),
                ('notes', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
