# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium_data', '0003_auto_20170619_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='dataset',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='dth',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='genus',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='map_reference',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='species',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
    ]
