# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbarium_data', '0005_auto_20170622_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='accession',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='common_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.RunSQL("ALTER TABLE herbarium_data_specimen ALTER accession SET DEFAULT ''"),
    ]
