# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_climate', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSensorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('station_order', models.PositiveSmallIntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_climate.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='sensors1',
            field=models.ManyToManyField(related_name='sensors', through='api_climate.StationSensorLink', to='api_climate.Sensor'),
        ),
        migrations.AddField(
            model_name='stationsensorlink',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_climate.Station'),
        ),
    ]
