# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_climate', '0003_auto_20160816_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='sensors',
        ),
    ]
