# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_climate', '0006_auto_20160816_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationsensorlink',
            options={'ordering': ('station_order',)},
        ),
        migrations.AddField(
            model_name='stationsensorlink',
            name='read_frequency',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
