# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_climate', '0017_auto_20170606_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='goes_id',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
