# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_remove_station_sensors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='sensors1',
            new_name='sensors',
        ),
    ]
