# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_auto_20160816_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sensors',
            field=models.ManyToManyField(related_name='stations', through='climate.StationSensorLink', to='climate.Sensor'),
        ),
    ]
