# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0011_auto_20160823_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='data_source',
            field=models.CharField(choices=[('G', 'Retrieved from GOES satellite message'), ('L', 'Retrieved from station data log')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='reading',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reading',
            name='qc_processed',
            field=models.BooleanField(default=False),
        ),
    ]
