# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models

def load_settings(apps, schema_editor):
    Setting = apps.get_model("climate", "Setting")
    Setting(
        name="receiving_data",
        value="0"
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0013_setting'),
    ]

    operations = [
        migrations.RunPython(load_settings)
    ]
