# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0014_auto_20160906_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='read_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
